on:
  push:
  pull_request:
name: Main workflow
jobs:
  codestyle:
    name: codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - uses: snok/install-poetry@v1.1.1
      - run: poetry install
      - run: poetry run black --check .
  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
          architecture: "x64"
      - uses: snok/install-poetry@v1.1.1
      - run: poetry install
      - run: poetry run mypy dianfan.py
